### ISSUE TITLE
Comma syntax / How to use :set for multiple columns?

### ISSUE THREAD

**Issue by adham-omran** [magit/emacsql#100]
Hey, I'm trying to update multiple columns using `set`.

```
(emacsql db [
                :update ir
                :set 'afactor := 1.2
                ]))
```
Works fine but
```
(emacsql db [
                :update ir
                :set 'afactor := 1.2,
                     'priority := 50
                ]))
```
Does not.

I was not able to find an example that helped me. How am I supposed to do it?

Thank you for the package I'm using it in my project!

**Comment by tarsius** [comment]
Use `[:update ir :set [(= afactor 1.2) (= priority 50)]]` (and to update just one column `[:update ir :set (= afactor 1.2)]`).
