### ISSUE TITLE
MELPA recipe fails without "next" branch

### ISSUE THREAD

**Issue by muradm** [magit/emacsql#103]
I was using emacs/straight.el/org-roam with `(org-roam-database-connector 'sqlite-builtin)`. And yesterday after updating emacs and refreshing packages with straight, i got "next branch not found" for `(use-package emacsql-sqlite-builtin :ensure t)`.

Is dropping "next" branch accidential?

**Comment by tarsius** [comment]
Indeed I did, or rather I renamed it forgetting that its name was being used in the melpa recipe. I've now reverted the rename.

**Comment by muradm** [comment]
Ok, thanks! it worked now :)
