### ISSUE TITLE
Test all back-ends

### ISSUE THREAD

**Issue by tarsius** [magit/emacsql#109]
I just added a `test` ci workflow based on #101. It currently tests the `sqlite`, `mysql` and `psql`.

The following back-ends are not being tested yet:

- [x] `sqlite-builtin` -- The Emacs build we use hasn't added support.
- [x] `sqlite-module` -- Fails because the dynamic library cannot be found. It appears to be where it is supposed to be though. Help welcome.
- [ ] `pg` -- I don't know what's wrong but it is broken.

It is important that we start testing the first two back-ends, because those are going to be the new default back-ends (depending on the Emacs version is used and whether Emacs was built with SQLite support).

Also, one test fails for Emacs 25.x, see #102.

**Comment by tarsius** [comment]
We are now testing the first two backends.

I still don't know what's wrong with `pg` and have no intention of figuring that out myself.

**Comment by ratsclub** [comment]
@tarsius We noticed that commenting the following line makes the `pg` backend just work. Maybe this helps understand where the problem is?

```elisp
(cl-defmethod emacsql ((connection emacsql-connection) sql &rest args)
  (let ((sql-string (apply #'emacsql-compile connection sql args)))
    ;; (emacsql-clear connection)
    (emacsql-send-message connection sql-string)
    (emacsql-wait connection)
    (emacsql-parse connection)))
```

**Comment by tarsius** [comment]
Thanks! I don't have time to look into this now, but will have a look at a later time.
