### ISSUE TITLE
Split low-level Emacs Lisp front-end for databases

### ISSUE THREAD

**Issue by proofit404** [magit/emacsql#11]
Maybe is it possible to split this package into something like `dbi` with low lovel api for execution raw sql queries and `emacsql` for generating those queries from dsl.  This will allow to build another tools on top of `dbi` library.

What do you think?

**Comment by wasamasa** [comment]
I'd welcome this as I've come to realize that SQL is a pretty alright DSL in its own and having a few helper functions (for fetching one value, one row, all rows, etc.) on top of a query/exec function taking the query string as argument with support for parameters is all I need.

**Comment by tarsius** [comment]
Emacs 29 will have built-in support for accessing SQLite databases. For earlier Emacs releases you can use https://github.com/pekingduck/emacs-sqlite3-api.

I have created alternative SQLite backends that use these implementations, see https://github.com/emacscollective/emacsql-sqlite-builtin. I will likely merge these into Emacsql itself and semi-deprecate the current SQLite backend.

I have no plans to implement some intermediate layer in Emacsql, such as

> a few helper functions (for fetching one value, one row, all rows, etc.) on top of a query/exec function taking the query string as argument with support for parameters is all I need.
