### ISSUE TITLE
emacsql probably the cause to freez emacs on macOS

### ISSUE THREAD

**Issue by catap** [magit/emacsql#117]
Greetings,

Long story short: I observe a wired bug in emacs on macOS, see: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=51336#5 and I was able to find some lead that is cause if this, and it leads to this repository https://debbugs.gnu.org/cgi/bugreport.cgi?bug=51336#46

The last message was written when I used e2b2df570d213cbaa995dd500a70b1ec95758925

**Comment by tarsius** [comment]
Do you know whether this is using the builtin or the module backend? And if so, does the other backend work without any issues? If its the module, did you try recreating it with the Emacs version you are currently using?

**Comment by catap** [comment]
I usually have opened magit status or a few of them, and as far as I know this is the only user of that sqlclient.

**Comment by catap** [comment]
So, right now I've run magit at MacPorts repo and emacs is frozen.

It had happened not each time, but frequent enough.

And removing of forge from that repo... helps!

**Comment by catap** [comment]
Nope, it's innocent. I can reproduce the issue without magit and emacsql.
