### ISSUE TITLE
MELPA version broken

### ISSUE THREAD

**Issue by sp1ff** [magit/emacsql#122]
Perhaps this was intentional (since this library is being deprecated), but commit [c786ea159facf5892e9c4e5b7bdda44da95cd62e](https://github.com/magit/emacsql/commit/c786ea159facf5892e9c4e5b7bdda44da95cd62e), which is the current build in MELPA, contains a bunch of comments that are missing the ";;" comment markers. This leads to dependencies, which still `require` the library to fail with unhelpful error messages.

**Comment by tarsius** [comment]
I've fixed that now. Thanks for the report.
