### ISSUE TITLE
`group-concat` does not work as expected with native

### ISSUE THREAD

**Issue by PatrickNorton** [magit/emacsql#127]
This appears to be the underlying issue behind https://github.com/org-roam/org-roam/issues/2393 and https://github.com/org-roam/org-roam-ui/issues/289.

Org-roam-ui queries its database using a query like the following (simplified to provide an MRE)
```elisp
(emacsql (org-roam-db) [:select [(funcall group-concat tag)]
                       :as tags
                       :from nodes
                       :left-join tags
                       :on (= id node-id)
                       :group :by id])
```
While one would expect this to return a list of lists of tags (i.e. `(("tag1" "tag2") ("tag1" "tag3"))`), it instead just returns the first tag from each entry (i.e. `("tag1" "tag1")`). In particular, the expected behavior was the behavior of the now-removed `emacsql-sqlite` backend.

My belief is that this is related to the call to `read` in `emacsql-send-message` (`emacsql-sqlite-builtin.el`, line 67); the string we try to read here looks like `"\"tag1\"\,\"tag2\""` but reading that will only return the first string, since that's the only symbol.

**Comment by tarsius** [comment]
Thanks for the report!
