### ISSUE TITLE
Issue with value that has embedded periods?

### ISSUE THREAD

**Issue by analyticd** [magit/emacsql#30]
I can work the examples for sqlite in the README.md fine. I have a small existing sqlite3 db that has the following content in a particular table:

sqlite> select id, content, created, filename from nuggets;
1|<sect level=1>test0</sect> . This is my first freex nugget. . This is another piece of text. . I link to journal like so|2016-11-30 20:20:24.173502|test0.freex
2|<sect level=1>journal</sect> . hello, this is my journal . paragraph 1 . <file>page1.freex</file> . <file>journal - test0.freex</file>|2016-12-18 20:58:20.174029|journal.freex
3|<sect level=1>page1</sect> . This is part of my journal . <file>page1 - paragraph 1.freex</file>|2016-12-18 21:17:19.464719|page1.freex
4|this is a region to be turned into a nugget . This is edited outside the journal|2016-12-18 21:17:52.696044|page1 - paragraph 1.freex
5|This is some text for the paragraph 1 nugget . Here is a link back to journal|2016-12-18 21:17:52.755955|paragraph 1.freex
6|This is some text point to test0 filename: journal.freex . id: 2 . aliases: <aliases>2</aliases> . tag-parents: <tag-parents>2</tag-parents> . tag-children: <tag-children>2</tag-children> . modtime: 2016-12-18 13:53:41 . |2016-12-18 21:59:17.344417|journal - test0.freex
7|<sect level=1>lisp</sect> . You can use freex-meta-find to create a new nugget easily . that is how i created the journal nugget|2016-12-18 22:06:12.215085|lisp.freex

If I do 

    (defvar db (emacsql-sqlite "~/Documents/freex/freex.db"))

    (emacsql db [:select [filename]
                :from nuggets])

it works (same for id and created columns), but if I try to get the content column values via

    (emacsql db [:select [content]
                 :from nuggets])

it fails. Is emacsql perhaps having an issue with the embedded periods, .,  in the content column values? The error written to *Messages* is: Invalid read syntax: ". in wrong context"

**Comment by skeeto** [comment]
EmacSQL is not intended to interact with arbitrary databases. All text
values must be stored as printed s-expressions. When EmacSQL inserts a
value, it inserts its printed form and reads it back in with the reader
in future queries. It would be unusual for non-EmacSQL databases to have
this property.

Your XML strings are definitely not s-expressions, so EmacSQL can't read
them.

**Comment by analyticd** [comment]
I see, thanks Skeeto. Trying to port the emacs-freex project to use emacsql to free it from its current python db interface. Maybe I'll figure out a way to still use it. emacsql is really cool, thanks for it.

**Comment by KrullBorg** [comment]
> EmacSQL is not intended to interact with arbitrary databases. All text values must be stored as printed s-expressions. When EmacSQL inserts a value, it inserts its printed form and reads it back in with the reader in future queries. It would be unusual for non-EmacSQL databases to have this property. Your XML strings are definitely not s-expressions, so EmacSQL can't read them.

hi, i have the same problem, but with ")" (not only) in field content (in a postgresql db)

is there a solution? or emacsql works only with some text content?

thanks in advance
