### ISSUE TITLE
Select queries does not return column names

### ISSUE THREAD

**Issue by lokedhs** [magit/emacsql#36]
There seems to be no way to find the column names in a result.

Ideally, there should be some kind of extra argument to the `emacsql` function that tells it to return the column names in addition to the actual data.

**Comment by skeeto** [comment]
This is something that each database driver would have to handle, but 
there's currently no interface in the driver for it. For some drivers 
that drive an interactive command line interface, such as mysql and 
psql, it may not even be possible.
