### ISSUE TITLE
Relevant full text search (SQLite FTS5 and/or SQLite extensions)

### ISSUE THREAD

**Issue by dandersonw** [magit/emacsql#40]
I am developing an application where I would like to use full text search, and moreover full text search that returns results in order by relevance.

Since I am using a SQLite database, my first thought was to use SQLite's FTS5 built in relevance sort, at least as a baseline, but it appears that the SQLite amalgamation emacsql uses predates FTS5.

My second thought was to use a C extension, but I don't see a way to load an SQLite extension in emacsql. I tried to run ` (emacsql db "select load_extension('/path/to/relevance-extension');")` but I got a `not authorized` error.

I was reading through the issue log and it seems like you don't plan to add any new features, so I wonder if you might accept a PR with a solution to one of the above issues. I am not really familiar with the subject matter, but I might be able put something together.

Do you have any advice?

**Comment by skeeto** [comment]
There's not any specific reason to keep SQLite at its current version in 
EmacSQL. FTS5 is really just a matter of dropping an updated 
amalgamation source in place and tweaking the compiler flags to enable 
it. I just haven't taken the time to update SQLite. I'd like to stop 
supplying pre-built binaries anyway, instead making a plain C compiler a 
required dependency. The code that downloads pre-build binaries could be 
ripped out. Tossing it would make the process of upgrading SQLite even 
easier.

The ability to load an extension would be nice. It seems the only thing 
that needs to happen is a call to sqlite3_enable_load_extension() in the 
C part of EmacSQL. I'll accept PR for something like this.

**Comment by alphapapa** [comment]
I would really like it if it were updated to use FTS5.  :)  I'll happily forego precompiled binaries as well.

**Comment by alphapapa** [comment]
Oh, wait, it already has been?  Slightly confused... does this issue just need to be closed?  Or does the readme need to be updated to mention FTS5, etc?

**Comment by skeeto** [comment]
FTS5 was enabled in 62d3915 three months ago:

https://github.com/skeeto/emacsql/blob/75ac0448a5965c82c616c862cab180c241110fd2/sqlite/Makefile#L6

The issue wasn't closed since extension loading wasn't addressed. Thanks 
for pointing out the issue in the README.

**Comment by dandersonw** [comment]
Thanks for including the new version of SQLite. I suspect that that will be enough for now, although I hadn't gotten around to evaluating the results since I ran into some other issues (and became personally busy etc).

I will make some time this weekend to get back into what I was doing and confirm if I will do anything right now about loading extensions.
