### ISSUE TITLE
Allowance for using DISTINCT keyword in aggregate function for SQLite

### ISSUE THREAD

**Issue by strait** [magit/emacsql#41]
I didn't find any obvious way to make the funcall operator work for counting distinct column values so I used `:count [:distinct file-name]`, which doesn't seem to be a documented recommendation in this context. 

I'm really liking this emacsql. Thanks for continuing to refine it!

**Comment by skeeto** [comment]
Hmm, I hadn't anticipated this one in the SQL compiler. This is some 
really weird syntax, so I don't think there was a way to use DISTINCT 
with aggregates.

But it turns out it wasn't difficult to add. Use it like this:

    [:select (funcall count :distinct x) :from foo]
