### ISSUE TITLE
Why is emacsql-error not declared as an error condition?

### ISSUE THREAD

**Issue by jmay** [magit/emacsql#70]
It would be useful to be able to handle database errors with `condition-case`. But the `emacsql-error` condition is never explicitly declared as an error in `emacsql.el`. Is this intentional? When I add something like
```elisp
(define-error 'emacsql-error "SQL Error")
```
then error-handling seems to work fine.

The sqlite adapter adds some additional conditions, like `emacsql-constraint`, which can also be declared this way.

**Comment by tarsius** [comment]
> But the `emacsql-error` condition is never explicitly declared as an error in `emacsql.el`.

I believe it is:

```elisp
(defmacro emacsql-deferror (symbol parents message)
  "Defines a new error symbol  for EmacSQL."
  (declare (indent 2))
  (let ((conditions (cl-remove-duplicates
                     (append parents (list symbol 'emacsql-error 'error)))))
    `(prog1 ',symbol
       (setf (get ',symbol 'error-conditions) ',conditions
             (get ',symbol 'error-message) ,message))))

(emacsql-deferror emacsql-error () ;; parent condition for all others
  "EmacSQL had an unhandled condition")
```

Tell me if I am missing something.
