### ISSUE TITLE
Invalid read syntax ")"

### ISSUE THREAD

**Issue by dericbytes** [magit/emacsql#76]
I get  `Invalid read syntax ")"` when  ``datetime('now') `` is in a column

```
 (defun pkb-select-table-columns (table-name)
      ""
      (emacsql db
	       [:pragma (funcall table_info $i1)]
	       table-name))
```

error on running this

```
 (pkb-select-table-columns 'keymap_keys)
```

running command directly in sql prompt

```
sqlite> PRAGMA table_info('keymap_keys');
0|function_name|TEXT|0||1
1|desc|TEXT|0||0
2|key|TEXT|0||0
3|registered|TEXT|0|datetime('now')|0
```

**Comment by tarsius** [comment]
EmacSQL is not intended to interact with arbitrary databases, but I believe you are trying to access a database that was created with something other than EmacSQL (I don't think `datetime('now')` is something that EmacSQL would ever put there. Tell me if I guessed wrong.

Also see the new [FAQ](https://github.com/magit/emacsql#faq).
