### ISSUE TITLE
emacsql-sqlite returns "middleware out of memory" on Termux (Android)

### ISSUE THREAD

**Issue by bram85** [magit/emacsql#78]
Calling anything database related, such as:

```lisp
(emacsql-sqlite "/data/data/com.termux/files/usr/tmp/test.db")
```

always results in "middleware out of memory" on Termux.

The binary has been compiled with clang version 12.0.0.

**Comment by tarsius** [comment]
Please check whether 374726060d74df0e2bcb9d0355ff41e2c400ed30, which was applied in February to fix #91, also fixes this issue, making #79 unnecessary.

**Comment by tarsius** [comment]
> Please check whether https://github.com/magit/emacsql/commit/374726060d74df0e2bcb9d0355ff41e2c400ed30 [...] fixes this issue,

I am going to assume that it did.

**Comment by bram85** [comment]
I checked months ago and it was fixed indeed. But somehow my message didn't come through.

**Comment by tarsius** [comment]
Yippee :smile:
