### ISSUE TITLE
Cannot build emacsql sqlite binary with gcc

### ISSUE THREAD

**Issue by wang1zhen** [magit/emacsql#80]
I was not able to build sqlite binary with gcc as the compiler, see [my issue for org-roam](https://github.com/org-roam/org-roam/issues/1718#issue-957284059), and after I switched to clang, it seems to be fine. Is it expected behaviour?

**Comment by skeeto** [comment]
The "internal compiler error: Segmentation fault" is GCC crashing while 
compiling SQLite. This is very unexpected. Either your distribution has 
given you a broken compiler or you've got some kind of local hardware 
issue (bad memory, bad hard drive, etc.) that has perhaps corrupted your 
local GCC installation.

**Comment by wang1zhen** [comment]
> 
> The "internal compiler error: Segmentation fault" is GCC crashing while compiling SQLite. This is very unexpected. Either your distribution has given you a broken compiler or you've got some kind of local hardware issue (bad memory, bad hard drive, etc.) that has perhaps corrupted your local GCC installation.

I am on Debian sid with `build-essential` which includes `gcc` freshly installed, and actually I have tried to remove and reinstall gcc for several times, which seems to be of no use.

**Comment by skeeto** [comment]
This works fine for me:

```dockerfile
FROM debian:sid-slim
RUN apt-get update && apt-get install --yes build-essential emacs-nox git
RUN git clone https://github.com/cbbrowne/pg.el pg
RUN git clone https://github.com/skeeto/emacsql
WORKDIR emacsql
CMD make check
```

    docker build -t emacsql-test .
    docker run --rm emacsql-test

Which indicates that its definitely some local installation issue. Perhaps one of GCC's dependencies — e.g. libgmp10, libisl23, libmpc3, libmpfr6 (all: `dpkg -s gcc-10 | grep Depends`) — are corrupted?

**Comment by wang1zhen** [comment]
Thank you for your reply, as I have already compiled binary with clang, I am not able to reproduce it, would you please tell me how to delete the compiled emacsql file so that I may reproduce it?

**Comment by tarsius** [comment]
> please tell me how to delete the compiled emacsql file

Use `rm sqlite/emacsql-sqlite`.

I am closing this because I trust Christopher's conclusion that this is a local issue.
