### ISSUE TITLE
Is it possible to store JSON values?

### ISSUE THREAD

**Issue by chrish-21** [magit/emacsql#89]
SQLite has the ability to store JSON values (https://www.sqlite.org/json1.html)

Is it possible to insert and query JSON with emacsql?

When I create a table like this:
```
  (emacsql db
           [:create-table test ([col])])
```

Trying to insert a JSON object with escaped double quotes results in the string being stored as `"{\"foo\":\"bar\"}"`
```
  (emacsql db
           [:insert :into test :values (["{\"foo\":\"bar\"}"])])
```

Trying to call a SQLite function in values, doesn't call the function but stores it as a value `(funcall json_object "foo" "bar")`
```
  (emacsql db
           [:insert :into test :values ([(funcall json_object "foo" "bar")])])
```

I want the value to be stored as `{"foo":"bar"}` so that it is possible to use SQLite functions like json_extract or json_each

**Comment by tarsius** [comment]
EmacSQL stores all values using their printed form (`prin1-to-string`), so this is not possible. See the new [FAQ](https://github.com/magit/emacsql#faq).
