### ISSUE TITLE
Update vendored SQLite

### ISSUE THREAD

**Issue by Titan-C** [magit/emacsql#98]
I know from #40 you don't really want to keep vendoring SQLite, yet after 4 years could we have an update?
I just tested with the latest amalgamation 3.38.4 and it does what I need.
I want to use the syntax capabilities of "upsert" and "on conflict"

**Comment by tarsius** [comment]
I'll soon add two alternative SQLite backends, which do not use the ventored file. See #86. I am undecided whether to update the current backend, because the new backends will semi-deprecate it and updating isn't risk free.

**Comment by tarsius** [comment]
I've updated to the latest version.

If there are any new features that require an opt-in that you would like to use, then please let me know. For now I haven't enabled any.
